### ISSUE TITLE
wetvoorstel omtrent drugs

### ISSUE THREAD

**Issue by Verzaakman3108** [Veenendaal-Roleplay/IC-Wetboek#3]
Wanneer je een issue wil aanmaken kan je dit doen voor een van de volgende redenen waaronder:

een wetswijziging;
een wetsvoorstel; Drugs productie bezit en distributie illegaal maken.
een vraag betreffende het wetboek;
een fout in het wetboek; atm. is het legaal om drugs te produceren op zak te hebben en te verkopen.
overige wetboek gerelateerde issues.
Het maken van een issue voor ongeldige redenen leidt tot het niet behandelen van de issue.

De issues zijn niet gemaakt voor in-game problemen of persoonlijke situaties. Zorg er dus voor dat het puur om het wetboek gaat.

**Comment by Yours-Truely** [comment]
Met ingang 32 minuten geleden, zie wetswijziging 2022003
